name: Auto Commit & Push

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit and Push
        uses: offensive-vk/auto-commit-push@v8
        with:
          name: 'Your Name'
          email: 'your@email.com'
          message: 'Commit Message'
          branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
